name: Build Android APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v3
        with:
          buildozer_version: stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
